---

- name: Add the Google APT GPG key.
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add the Kubernetes repository.
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial-unstable main
