- name: Reset the K8s cluster with kubeadm.
  command: kubeadm reset

- name: Remove all containers.
  shell: docker rm -f $(sudo docker ps -qa)
  ignore_errors: true

- name: Remove all images.
  shell: docker rmi -f $(sudo docker images -qa)
  ignore_errors: true

- name: Remove Cluster status file.
  file:
    path: /opt/k8s-cluster-exists-YES
    state: absent

- name: Remove Cluster status Dashboard file.
  file:
    path: /opt/k8s-cluster-dashboard
    state: absent

- name: Remove Cluster status Heapster file.
  file:
    path: /opt/k8s-cluster-heapster
    state: absent

- name: Remove the Ingress status file.
  file:
    path: /opt/k8s-cluster-ingress
    state: absent

- name: Remove the kubectl admin.conf file.
  file:
    path: "/home/{{ ansible_user }}/admin.conf"
    state: absent
