---

- name: Check if Cluster is up and running.
  stat:
    path: /opt/k8s-cluster-exists-YES
  register: stat_result

- include: destroy-k8s.yml
  when: stat_result.stat.exists == True

- name: Remove Cluster status file.
  file:
    path: /opt/k8s-cluster-exists-YES
    state: absent
  when: stat_result.stat.exists == True

- name: Remove Cluster status Dashboard file.
  file:
    path: /opt/k8s-cluster-dashboard
    state: absent
  when: stat_result.stat.exists == True

- name: Remove Cluster status Heapster file.
  file:
    path: /opt/k8s-cluster-heapster
    state: absent
  when: stat_result.stat.exists == True
