---

- name: Copy the admin.conf file into the user home
  copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: /home/lanets/
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Add the EXPORT statement to the user.
  lineinfile:
    dest: /etc/profile
    line: 'export KUBECONFIG=$HOME/admin.conf'
