---

- name: Download the manifests files for Heapster.
  git:
    repo: https://github.com/kubernetes/heapster.git
    dest: /opt/heapster
    depth: 1

- name: Deploy the Heapster manifests.
  shell: kubectl apply -f /opt/heapster/deploy/kube-config/influxdb/ --kubeconfig=/etc/kubernetes/admin.conf
  args:
    creates: /opt/k8s-cluster-heapster

- name: TEMPORARY Create a text file to show that the Dashboard was successfully created. TEMPORARY
  file:
    path: /opt/k8s-cluster-heapster
    state: touch
